# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn

      - name: Run build server 1
        working-directory: "packages/server-1"
        run: yarn build

      - name: Run build server 2
        working-directory: "packages/server-2"
        run: yarn build

      - name: Copy project to digital ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "~/app/property-value-api"
          
      - name: Restart servers
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: deploy@167.172.143.12
          privateKey: ${{ secrets.SSH_KEY }}
          command: |
            pm2 restart server-1
            pm2 restart server-2





